services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insight-docs
    volumes:
      - postgres_data:/var/lib/postgresql/data


  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    environment:
      QDRANT__STORAGE__PATH: /qdrant/storage
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: